### ISSUE TITLE
Cannot read property "tzid" of undefined

### ISSUE THREAD

**Issue by sebay00** [kewisch/ical.js#140]
Hi There,

I'm sorry to bother you, I just started to work with ICS. And Thanks god, I found your lib. 
However, I can't make it work. 

Here's my error : 

```
TypeError: Cannot read property 'tzid' of undefined
    at Object.ICAL.Event.Event._setTime (/app/node_modules/jsical/build/ical.js:6504:44)
    at Object.startDate (/app/node_modules/jsical/build/ical.js:6407:12)
    at getICS (/app/lib/routes/bookings.js:123:21)
    at wrapICS (/app/lib/routes/bookings.js:84:12)
    at tryCatcher (/app/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/main/promise.js:466:31)
    at Promise._settlePromiseAt (/app/node_modules/bluebird/js/main/promise.js:545:18)
    at Promise._settlePromises (/app/node_modules/bluebird/js/main/promise.js:661:14)
    at Async._drainQueue (/app/node_modules/bluebird/js/main/async.js:79:16)
    at Async._drainQueues (/app/node_modules/bluebird/js/main/async.js:89:10)
    at Async.drainQueues (/app/node_modules/bluebird/js/main/async.js:14:14)
    at process._tickCallback (node.js:419:13)
```

I watched the code, and I guess it's the line `prop.setParameter('tzid', time.zone.tzid);` in _SetTime. 
And it seems logical, because I'm doing something like this to set up my start and end date : 

```
event.startDate = new Date("2015-03-19T17:00:00");
```

And there is no `startDate.zone` in it. 
I think that's a doc problem ? Or I may be an asshole. It happens sometime. :wink: :stuck_out_tongue: 

Someone can Help me ?

Seb

**Comment by kewisch** [comment]
Hey Seb, since the builtin Javascript Date object doesn't support timezones, we have the class `ICAL.Time`. What you should be able to do is:

```
event.startDate = ICAL.Time.fromString("2015-03-19T17:00:00");
```

**Comment by sebay00** [comment]
You forgot the `new` but I forgive you :stuck_out_tongue: (Told you, I was a jerk :wink: )

Cheers mate, you and your lib help me out a lot.

**Comment by kewisch** [comment]
`ICAL.Time.fromString` should be a static method without using `new` ?

**Comment by sebay00** [comment]
Oh, my bad :disappointed:  It was working with new, anyway. :smile: 

A bit off topic but can we add some attendees and RSVP options with your lib ?

**Comment by kewisch** [comment]
You can add any property you want with the Property/Component level API using `event.component.addProperty()`
