### ISSUE TITLE
Invalid parameters in 'DEATHDATE;19900615T000000'

### ISSUE THREAD

**Issue by skjnldsv** [kewisch/ical.js#379]
Looking at https://tools.ietf.org/html/rfc6474#section-2.3 and https://tools.ietf.org/html/rfc6350#section-6.2.5
This throw an error directly for me.
``` json
{
  "message": "Invalid parameters in 'DEATHDATE;19900615T000000'",
  "name": "ParserError",
  "stack": "    at new ParserError (https://dev.skjnldsv.com/custom_apps/contacts/js/contacts.js:6178:13)
    at Function../node_modules/ical.js/build/ical.js.ICAL.parse.parser._handleContentLine (https://dev.skjnldsv.com/custom_apps/contacts/js/contacts.js:6324:15)
    at https://dev.skjnldsv.com/custom_apps/contacts/js/contacts.js:6208:14
    at Function../node_modules/ical.js/build/ical.js.ICAL.parse.parser._eachLine (https://dev.skjnldsv.com/custom_apps/contacts/js/contacts.js:6667:11)
    at Object.parser [as parse] (https://dev.skjnldsv.com/custom_apps/contacts/js/contacts.js:6207:12)
    at new Contact (https://dev.skjnldsv.com/custom_apps/contacts/js/contacts.js:43387:63)
    at https://dev.skjnldsv.com/custom_apps/contacts/js/contacts.js:44522:21
    at Array.reduce (<anonymous>)
    at parseVcf (https://dev.skjnldsv.com/custom_apps/contacts/js/contacts.js:44519:17)
    at Store._callee8$ (https://dev.skjnldsv.com/custom_apps/contacts/js/contacts.js:45177:91)"
}
```

**Comment by kewisch** [comment]
This looks like an error in the spec instead? https://www.rfc-editor.org/errata/eid4556
