### ISSUE TITLE
Cannot run tests

### ISSUE THREAD

**Issue by dilyanpalauzov** [kewisch/ical.js#506]
I do
```
$ git checkout origin/main
(f52354c...) $ npm install
(f52354c...) $ npm run prepare
(f52354c...) $ npm run test


> ical.js@1.5.0 test
> grunt test-node

Running "test-node" task

Running "performance-update:upstream" (performance-update) task
>> Not on master, also comparing against master branch

Running "mochacli:performance" (mochacli) task
Version ICAL_previous not found, skipping
Version ICAL_previous not found, skipping
Version ICAL_previous not found, skipping
Version ICAL_previous not found, skipping
Version ICAL_upstream not found, skipping


  iterator
    1) "before all" hook for "benchmark"

  ICAL parse/stringify
    2) "before all" hook for "benchmark"

  rrule
    3) "before all" hook for "benchmark"

  ICAL.Time

latest: subtract date x 173,102 ops/sec ±2.81% (83 runs sampled)
latest: add duration x 313,662 ops/sec ±4.08% (76 runs sampled)
latest: create and clone time x 124,287 ops/sec ±4.10% (73 runs sampled)
latest: toUnixTime x 160,632,332 ops/sec ±2.39% (80 runs sampled)
latest: dayOfWeek x 10,331,716 ops/sec ±3.66% (78 runs sampled)
latest: weekNumber x 6,391,230 ops/sec ±3.14% (84 runs sampled)
upstream: subtract date: 
    ✓ benchmark (33240ms)


  1 passing (33s)
  3 failing

  1) iterator
       "before all" hook for "benchmark":
     TypeError: ICAL.parse is not a function
      at Context.<anonymous> (test/performance/iterator_test.js:16:19)
      at /git/ical.js/test/helper.js:229:9
      at /git/ical.js/test/helper.js:200:9
      at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)

  2) ICAL parse/stringify
       "before all" hook for "benchmark":
     Uncaught TypeError: ICAL.parse is not a function
      at /git/ical.js/test/performance/parse_test.js:7:19
      at /git/ical.js/test/helper.js:228:9
      at /git/ical.js/test/helper.js:200:9
      at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)

  3) rrule
       "before all" hook for "benchmark":
     TypeError: Cannot read properties of undefined (reading 'fromString')
      at Context.<anonymous> (test/performance/rrule_test.js:7:23)
      at processImmediate (node:internal/timers:466:21)



Warning:  Use --force to continue.

Aborted due to warnings.
```

**Comment by kewisch** [comment]
I've reworked this in the `es6` branch so it should get easier. `grunt test-node` runs all the tests, and the perf tests are somwhat flaky. Try `grunt test-node:unit` which will give you most of the relevant tests.

**Comment by dilyanpalauzov** [comment]
On my system the performance tests are failing most of the time with the message above.

**Comment by kewisch** [comment]
The performance tests are pretty broken in `main`. I've noticed one issue with the perf tests even in the es6 branch, and - lets be honest - perf tests are highly subjective based on machine performance, and within a certain delta it doesn't make a major difference.

For the sake of pull requests it should be sufficient to run the normal tests (unit + acceptance). If you go to the es6 branch (just force pushed there for #538, you might might need to pull again) and just run npm run test, do you get any errors?

**Comment by dilyanpalauzov** [comment]
On the es6-brach the tests do complete (in 1 out of 1 tries).

**Comment by kewisch** [comment]
Nice! Hoping to get it merged soon, if you are interested feel free to skim over #538 and lmk your thoughts (which I now see you have — thank you!)
